# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target 'banano-quest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for banano-quest
  pod 'PocketEth', '~> 0.0.3'

  pod 'SidebarOverlay', :git => 'git@github.com:pokt-network/SidebarOverlay.git', :branch => 'develop'
  pod 'FlexColorPicker', :git => 'https://github.com/RastislavMirek/FlexColorPicker', :branch => 'master'
  pod 'SwiftHEXColors'
  pod 'BiometricAuthentication'
  pod 'HDAugmentedReality', '~> 2.4'

  target 'banano-questTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'banano-questUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
